apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-rocks-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-rocks-server
  template:
    metadata:
      labels:
        app: fiap-rocks-server
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command:
          - sh
          - -c
          - until nc -z -v -w30 mysql 3306; do echo "Aguardando MySQL..."; sleep 5; done
          
      containers:
      - name: fiap-rocks-server
        image: caiojorge/fiap-rocks:latest
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: dbcontrolf2
        - name: DB_USER
          value: myuser
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user-password
        ports:
        - containerPort: 8083
